cantrip/config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root                        'static_pages#home'
  get 'legal'    =>           'static_pages#legal'
  get 'about'   =>            'static_pages#about'
  get 'contact' =>            'static_pages#contact'
  get 'character_creator' =>  'static_pages#character_creator'
  get 'signup' =>             'users#new'
  get    'login'   =>         'sessions#new'
  post   'login'   =>         'sessions#create'
  delete 'logout'  =>         'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users
end

cantrip/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def character_creator
  end

  def legal
  end

  def contact
  end
end

cantrip/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

cantrip/app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
	<h1>About</h1>
	<p>
		Try
	<a href="http://www.google.com/">Google</a>
	until I do more work.
	</p>

cantrip/app/views/static_pages/character_creator.html.erb
<% provide(:title, "Character Creator") %>
	<h1>Character Creator</h1>
	<p>
		This page will be used to create a D&D character.
	</p>

cantrip/app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  I'll see you at the next meeting.
</p>

cantrip/app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Cantrip</h1>

  <h2>
    An online companion to the Dungeons & Dragons roleplaying game.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

cantrip/app/views/static_pages/legal.html.erb
<% provide(:title, "Legal") %>
	<h1>Legal</h1>
	<p>
		Try
	<a href="http://www.google.com/">Google</a>
	until I do more work.
	</p>